### ISSUE TITLE
区分をカラムからテーブルにする

### ISSUE THREAD

**Issue by lime1024** [lime1024/medireco#188]
# やること
- [x] `medical_bills` テーブルにカラムとしてあるが、`classifications` テーブルとして独立させる #189 
- [x]  `medical_bills` テーブルの `classification` カラムを削除する #190 
- [x] アソシエーションを修正する (`medical_bill._classification` の `_` をやめる) #190
- [x] `medical_bill.classification_id` の NULL を許可しない #190

# 移行手順
ローカルにデータ持ちたくないのと、使ってみたいので基本 web の heroku で行う

- [x] ローカルで以下の手順で試す
- [x] heroku に web からログインする
- [x] 現在の DB のデータを [Heroku PGBackups](https://devcenter.heroku.com/articles/heroku-postgres-backups) で手動で dump する
- [ ] #189 を master にマージしてデプロイする
- [ ] heroku の web から Run console で bash で入る
- [ ] seed データを流す
```sh
bundle exec rails db:seed ENV='production'
```
- [ ] 事前に対象 (`medical_bill.classification_id = nil`) の数を数える
```sh
bundle exec rails r 'require "#{Rails.root}/lib/classification_migrator"; puts ClassificationMigrator.classification_id_nil_count'
```
- [ ] 移行スクリプトを実行する
```sh
bundle exec rails r 'require "#{Rails.root}/lib/classification_migrator"; ClassificationMigrator.execute'
```
- [ ] 事後に対象 (`medical_bill.classification_id = nil`) の数を数える
```sh
bundle exec rails r 'require "#{Rails.root}/lib/classification_migrator"; puts ClassificationMigrator.classification_id_nil_count'
```
- [ ] 事後の数が 0 になっていたら ok
